name: atividade_05
description: Descrição breve do projeto
version: 1.0.0 
environment:
  sdk: '>=2.18.0 <3.0.0' 

dependencies:
  http: ^1.2.2 
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0 

dev_dependencies:
  lints: ^2.0.0 