name: prova
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
